installs:
  apt:
    - name: Visual Studio Code (OSS)
      package: codium
      source_script: sources/vscodium.sh
    - name: Cheat Sheet
      package: cht.sh
    - name: duf - Disk Usage/Free Utility
      package: duf
    - name: duff - Duplicate File Finder
      package: duff
    - name: GNU stow
      package: stow
    - name: lsd - ls Deluxe
      package: lsd
    - name: Sublime Text 4
      package: sublime-text
      source_script: sources/sublimetext.sh
    - name: Qbittorrent
      package: qbittorrent
      source: ppa:qbittorrent-team/qbittorrent-stable
    - name: Zeal docs
      package: zeal
      source: ppa:zeal-developers/ppa
    - name: PDF Arranger
      package: pdfarranger
    - name: 7zip
      package: p7zip-full
    - name: Foliate
      package: foliate
    - name: tldr
      package: tldr
    - name: fzf - Fuzzy File Finder
      package: fzf
    - name: Brave Browser
      package: brave-browser
    - name: Proton VPN
      package: proton-vpn-gnome-desktop
      source_script: sources/protonvpn.sh
  flatpak:
    - name: Bitwarden
      package: com.bitwarden.desktop
    - name: Zen Browser
      package: app.zen_browser.zen
    - name: ZapZap (Unofficial Whatsapp)
      package: com.rtosta.zapzap
    - name: GearLever
      package: it.mijorus.gearlever
    - name: AppImagePool
      package: io.github.prateekmedia.appimagepool
  commands:
    - name: Calibre
      package: sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
    - name: Rust Programming Language
      package: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

uninstalls:
  apt:
    - name: LibreOffice
      package: libreoffice*
    - name: Transmission
      package: transmission*

settings:
  commands:
    - name: Enable Firewall
      command: sudo ufw enable
    - name: Set timezone to UTC
      command: sudo timedatectl set-timezone UTC
  scripts:
    - name: Disable touchscreen
      script: disable_touchscreen.sh
